name: CI Pipeline for WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout kode dari repositori
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Versi PHP yang akan digunakan
          extensions: mbstring, mysqli, dom, json
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: none

      # Step 3: Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist

      # Step 4: Setup WordPress testing environment
      - name: Set up WordPress testing environment
        env:
          WP_VERSION: latest
          WP_TESTS_DIR: /tmp/wordpress-tests-lib
          WP_CORE_DIR: /tmp/wordpress
        run: |
          bash ./.github/scripts/install-wp-tests.sh wordpress_db root '' localhost latest

      # Step 5: Run PHPUnit tests
      - name: Run PHPUnit tests
        env:
          WP_CORE_DIR: /tmp/wordpress
        run: |
          vendor/bin/phpunit
