name: CI Pipeline for WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      WP_VERSION: "5.7"  # Tentukan versi WordPress secara eksplisit, misalnya "5.7" atau "5.8"
      WP_DB_NAME: wordpress_test
      WP_DB_USER: root
      WP_DB_PASS: "Af@050602"
      WP_DB_HOST: 127.0.0.1
      WP_DB_PORT: 3307  # Gunakan port khusus

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1
        with:
          mysql version: '5.7'
          mysql database: "$WP_DB_NAME"
          mysql user: "$WP_DB_USER"
          mysql password: "$WP_DB_PASS"
          ports: "3307:3306"  # Mapping port container ke host

      - name: Set up WordPress testing environment
        run: |
          chmod +x .github/scripts/install-wp-tests.sh
          ./.github/scripts/install-wp-tests.sh "$WP_DB_NAME" "$WP_DB_USER" "$WP_DB_PASS" "$WP_DB_HOST" "$WP_DB_PORT" "$WP_VERSION"

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
